### ISSUE TITLE
Use with webpack

### ISSUE THREAD

**Issue by mshick** [stephband/jquery.event.move#28]
Do you have any suggestions for how I might use this properly with webpack? I can get it to function by providing jquery globally in the page, and then importing this (to get it in my bundle) by the explicit passing of a jquery object fails as webpack doesn't seem to allow it to export a function.

Example of non-working setup, but the way I think it _should_ work:

```js
var $ = "jquery";
require("jquery.event.move")($);
```

This always leads to a runtime error to the effect that the require is not exporting a function.

The only way I can make it work properly is to have window.jQuery defined, and to do `require("jquery.event.move")`.

**Comment by zhenyong** [comment]
@mshick 

u should require both:

require('jquery')
require('jquery.event.move')

**Comment by mshick** [comment]
@zhenyong I had a typo in my issue, so of course that wouldn't work... Globally requiring jquery before v3 was a pain, much easier now in my experience. Thanks.
