### ISSUE TITLE
Need 'movestart' on pointerdown

### ISSUE THREAD

**Issue by Bortxx** [stephband/jquery.event.move#29]
I know it is a feature to not have the 'movestart' event fire until there is a move but I need that event raised before there is any move for my own purposes. Looked at the code and there is a threshold value set to 6 which I thought if I set it to 0 would do the job but no. I even removed the code in the checkThreshold() that short circuits the function but no luck. 

What do I need to do to get the movestart event immediately on pointer down? or maybe fix it so threshold = 0 behaves as expected.

**Comment by stephband** [comment]
What's wrong with using mousedown or touchstart for this purpose?


––––––––––––
http://sound.io
http://cruncher.ch
http://stephen.band

**Comment by Bortxx** [comment]
Well, I liked what you did with the unification of events rather than having to deal with touch and mouse events separately and all other idiosyncrasies like 300ms delay, inconsistency between browsers, etc.  Also even with threshold set to 0, Abs(e.distY) won't report a value lower than 10 with touch. With mouse it is correct and I get a min of 1. So the touch move is ignored unless we move more than 10 units.

**Comment by stephband** [comment]
Initialising the bindings for move events without first checking whether we have started moving would be bad for the performance of other, everyday interactions, such as 'click'. Not critically bad, but bad nonetheless. I am not intending to change this.

In other news, jQuery.event.move is now jQuery 3 compatible. This is a first version, so if you have a chance please test and report any problems.

The underlying implementation is now vanilla DOM, so move events can also be used without jQuery.

**Comment by Bortxx** [comment]
That's OK. I could not deal with the limitations of this API anymore so I moved to jquery/PEP which does what I needed. https://github.com/jquery/PEP

**Comment by stephband** [comment]
Oh that's pretty cool. I didn't know about that polyfill. I'm going to try
that.

I always considered that move events would be superseded by pointer events,
so maybe that time has come.
