### ISSUE TITLE
move delay in mobile

### ISSUE THREAD

**Issue by eldyvoon** [stephband/jquery.event.move#32]
$('elem').bind('move',function(){

}

any idea it delay 1 second when use 'move' in mobile?

**Comment by stephband** [comment]
I just pushed an update that might help.

jQuery.event.move is now jQuery 3 compatible. This is a first version, so if you have a chance please test and report any problems.

The underlying implementation is now vanilla DOM, so move events can also be used without jQuery.

**Comment by stephband** [comment]
Closing, no news.
