### ISSUE TITLE
for ... of statements break Uglify JS2 and all but the latest browers

### ISSUE THREAD

**Issue by marvinklein** [stephband/jquery.event.move#35]
the `for ... of` statements break Uglify JS2 and all but the latest browsers. Can we rewrite this to use a more widely supported iteration syntax?

**Comment by stephband** [comment]
Oh, yes please. Are you volunteering? :)

**Comment by marvinklein** [comment]
https://github.com/stephband/jquery.event.move/pull/36

**Comment by aurmil** [comment]
+1, this loop makes this plugin incompatible with IE, even v. 11
thanks for the PR @marvinklein , works here :)

**Comment by stephband** [comment]
Merged pull request.
