### ISSUE TITLE
release 2.0.0

### ISSUE THREAD

**Issue by bnomei** [stephband/jquery.event.move#39]
there is no 2.0.0 release so bower can not update from 1.3.6 to 2.0.0. is this intended? why?

**Comment by stephband** [comment]
No, not intended. I didn't add bower support, so I didn't know something
had to be done. What needs to change?

**Comment by bnomei** [comment]
thanks for responding so quickly.

short: create a 2.0.0 release matching your `package.json` version and continue to do so in the future.

long story:
i think bower just parses your releases.
i am using [unslider](http://idiot.github.io/unslider/) which has build in support for your move and swipe libs, but when adding them via bower i only get move v.1.3.6. but that one has no jquery 3.x support so i got errors.

**Comment by stephband** [comment]
Ah, I see what you mean: I have forgotten to add a git tag 2.0.0. Ok, will
do, can't right now on my phone, but will do when I get behind a laptop.

**Comment by stephband** [comment]
I tagged it. *Should* work!

**Comment by bnomei** [comment]
does (almost) work. thanks. see next issue.
