### ISSUE TITLE
minification fails because of es6 features

### ISSUE THREAD

**Issue by bnomei** [stephband/jquery.event.move#40]
on line 101 char 12 you use `for ... of ...` which is es6 or with moz extension. I am prepending your js to mine then doing minification. since i am using jshint, jslint or eslint before minification it fails. I can tell my preprocessor to use es6 on your file only but it would be nice if you [include it too](http://stackoverflow.com/questions/27441803/why-does-jshint-throw-a-warning-if-i-am-using-const#27442276). just add to the head of your script...

```
/*jshint esversion: 6 */
```

**Comment by stephband** [comment]
I just merged the pull request https://github.com/stephband/jquery.event.move/pull/36/commits/cc87d443d3ce015edac246d830bfc0576ad33507 which gets rid of for...of in favour of while loops. Bumped to 2.0.1. SHould fix your problem.

**Comment by bnomei** [comment]
perfect and so quick. thanks so much.
