### ISSUE TITLE
touch device: page scrolling (in v 1.2)

### ISSUE THREAD

**Issue by jlgeering** [stephband/jquery.event.move#5]
Hey Stephen,

If I view the demo page (v 1.2) on a touch device (I tried with an iPad, a galaxy nexus and a nexus 7) I can move the red thing around, but cannot scroll the page around anymore.

I tried an older version (1.0.2) and the page scrolled normally.

cheers
JL

**Comment by NachtmannM** [comment]
I am using 1.3.6 and I still got the problem, that every CCS-overflow:scroll element does not scroll anymore. Am I missing a way to apply the fix?
